pipeline:

  deploy:
    image: docker
    commands:
      - docker deploy --compose-file docker-compose.yml influx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ MQTT_HOST, MQTT_USER, MQTT_PASS ]